config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }



  root to: 'public/homes#top'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :public do
    get 'homes/about'
    get "search" => "searches#search"

    resources :notifications, only: [:update]

    resources :nationalities, only: [:show]

    resources :post_players, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end


    get 'users/my_page' => 'users#my_page', as: :my_page
    get 'users/unsubscribe' =>'users#unsubscribe', as: :unsubscribe
    patch 'users/withdraw' =>'users#withdraw', as: :withdraw
    resources :users, only: [:index,:show,:edit,:update] do
      member do
        get :favorites
      end
      resource :relationship, only: [:create,:destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :cart_players,  only: [:index,:create,:update,:destroy] do
      collection do
        delete 'destroy_all'
      end
    end

  end



  namespace :admin do
    get '/' => 'homes#top'
    get "search" => "searches#search"

    resources :nationalities, only: [:show,:index,:edit,:create,:update,:destroy]

    resources :post_players, only: [:index,:show,:edit,:create,:update,:destroy] do
      resources :comments, only: [:destroy]
    end

    resources :users, only: [:index,:show,:edit,:update] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_player.rb
class PostPlayer < ApplicationRecord

  belongs_to :user
  belongs_to :nationality
  has_many :cart_players #ベストイレブン機能
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy #追記


  validates :name, presence: true
  validates :nationality_id, presence: true
  validates :body, presence: true

  scope :latest, -> { order(created_at: :desc) }  #desc = 降順
  scope :old, -> { order(created_at: :asc) }  #asc = 昇順
  scope :most_favorited, -> { includes(:favorites)}


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id)
    end
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @post_player = PostPlayer.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @post_player = PostPlayer.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @post_player = PostPlayer.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @post_player = PostPlayer.where("name LIKE?","%#{word}%")
    else
      @post_player = PostPlayer.all
    end
  end

end

app/controllers/admin/post_players_controller.rb
class Admin::PostPlayersController < ApplicationController
  before_action :check_post_player_existence, only: [:show, :edit, :update, :destroy]


  def index
    @post_players=PostPlayer.page(params[:page]).per(10).order(created_at: :desc)
  end

  def show
    @post_player=PostPlayer.find(params[:id])
    @comment=Comment.new
  end

  def edit
    @post_player=PostPlayer.find(params[:id])
  end

  def update
    @post_player=PostPlayer.find(params[:id])
    if @post_player.update(post_player_params)
      flash[:notice] = "投稿編集完了"
      redirect_to admin_post_player_path(@post_player.id)
    else
      render :edit
    end
  end

  def destroy
    @post_player = PostPlayer.find(params[:id])
    @post_player.destroy
    redirect_to admin_post_players_path
  end


  private

  def post_player_params
    params.require(:post_player).permit(:name, :body, :nationality_id)
  end

  def check_post_player_existence
    @post_player=PostPlayer.find_by(id: params[:id])
    unless @post_player
      redirect_to admin_post_players_path
    end
  end

end

app/helpers/admin/post_players_helper.rb
module Admin::PostPlayersHelper
end

app/views/admin/post_players/edit.html.erb
<% if @post_player.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @post_player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>



<div class="container">
  <%= form_with model: [:admin, @post_player], local: true , class: 'col-5 mx-auto my-5' do |f| %>
  <div class="row form-group">
    <%= f.label :'選手名' %>
    <%= f.text_field :name, class: 'form-control post_player_name' %>
  </div>

  <div class="row form-group">
    <%= f.label :'国籍', class: 'mr-3' %>
    <%= f.collection_select :nationality_id, Nationality.all, :id, :name, include_blank: "選択して下さい", class: 'form-control post_player_nationality' %>
  </div>


  <div class="row form-group">
    <%= f.label :'選手紹介文' %>
    <%= f.text_area :body, class: 'form-control post_player_body' %>
  </div>
  <div class="row form-group">
    <%= f.submit "Edit Player", class: 'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/admin/post_players/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'layouts/search' %>
  </div>
  <div class="row">
    <div>
      <h1 class="my-3"><strong>PLAYERS</strong></h1>
    </div>
  </div>
  <div class="row">
    <table class='table table-hover table-inverse'>
      <thead>
        <tr class="table-primary">
          <th>User</th>
          <th>Player Name</th>
          <th>Nationality</th>
          <th>Favorite</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <% @post_players.each do |post_player| %>
          <tr>
            <td><%= link_to post_player.user.name, admin_user_path(post_player.user_id) %></td>
            <td><%= link_to post_player.name, admin_post_player_path(post_player.id) %></td>
            <td><%= post_player.nationality.name %></td>
            <td>♥<%= post_player.favorites.count %></td>
            <td><%= link_to "Edit a player", edit_admin_post_player_path(post_player.id), class: "btn btn-success" %></td>
            <td><%= link_to "Delete", admin_post_player_path(post_player.id), class: "btn btn-danger", method: :delete, data: {confirm: "削除しますか？"} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="mx-auto"><%= paginate @post_players %></div>
  </div>
</div>

app/views/admin/post_players/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container">
  <div class="row">
    <div>
      <h1>Player detail</h1>
    </div>
    <div class="my-4 col-md-4 offset-1">
      <%= link_to "Edit a player", edit_admin_post_player_path(@post_player.id), class: "btn btn-success" %>
      <%= link_to "Delete", admin_post_player_path(@post_player.id), class: "btn btn-danger", method: :delete, data: {confirm: "削除しますか？"} %>
    </div>
  </div>
  <div class="row ">
    <div class="col-md-4">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th class="table-primary">Player Name</th>
            <td><%= @post_player.name %>　♥<%= @post_player.favorites.count %></td>
          </tr>
          <tr>
            <th class="table-primary">Nationality</th>
            <td><%= @post_player.nationality.name %></td>
          </tr>
          <tr>
            <th class="table-primary">Introduction</th>
            <td><%= @post_player.body %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row offset-1">
    <div>
      <h3>Comment　<%= @post_player.comments.count %></h3>
    </div>
  </div>
  <div class="row col-md-9 offset-1">
      <table class="table">
        <thead>
          <tr>
            <th>User</th>
            <th>Comment</th>
            <th>Date</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @post_player.comments.each do |comment| %>
          <tr>
            <td><%= comment.user.name %></td>
            <td><%= comment.body %></td>
            <td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= link_to "Destroy", admin_post_player_comment_path(comment.post_player, comment), method: :delete, data: {confirm: "削除しますか？"}, method: :delete, class: 'btn btn-danger' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
  </div>

</div>