config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }



  root to: 'public/homes#top'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :public do
    get 'homes/about'
    get "search" => "searches#search"

    resources :notifications, only: [:update]

    resources :nationalities, only: [:show]

    resources :post_players, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end


    get 'users/my_page' => 'users#my_page', as: :my_page
    get 'users/unsubscribe' =>'users#unsubscribe', as: :unsubscribe
    patch 'users/withdraw' =>'users#withdraw', as: :withdraw
    resources :users, only: [:index,:show,:edit,:update] do
      member do
        get :favorites
      end
      resource :relationship, only: [:create,:destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :cart_players,  only: [:index,:create,:update,:destroy] do
      collection do
        delete 'destroy_all'
      end
    end

  end



  namespace :admin do
    get '/' => 'homes#top'
    get "search" => "searches#search"

    resources :nationalities, only: [:show,:index,:edit,:create,:update,:destroy]

    resources :post_players, only: [:index,:show,:edit,:create,:update,:destroy] do
      resources :comments, only: [:destroy]
    end

    resources :users, only: [:index,:show,:edit,:update] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/nationality.rb
class Nationality < ApplicationRecord

  has_many :post_players, dependent: :destroy


  validates :name, presence: true, uniqueness: true


  def self.looks(search, word)
    if search == "perfect_match"
      @nationality = Nationality.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @nationality = Nationality.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @nationality = Nationality.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @nationality = Nationality.where("name LIKE?","%#{word}%")
    else
      @nationality = Nationality.all
    end
  end

end

app/controllers/admin/nationalities_controller.rb
class Admin::NationalitiesController < ApplicationController
before_action :check_nationality_existence, only: [:show,:edit, :update]

  def create
    @nationality = Nationality.new(nationality_params)
      if @nationality.save
        flash[:notice] = "国籍を登録しました。"
        redirect_to admin_nationalities_path
      else
        @nationalities = Nationality.page(params[:page]).per(8)
        render :index
      end
  end

  def show
    @nationality = Nationality.find(params[:id])
    @nationality_post_players=@nationality.post_players.page(params[:page]).per(10)
  end

  def index
    @nationalities = Nationality.page(params[:page]).per(8)
    @nationality = Nationality.new
  end

  def edit
    @nationality = Nationality.find(params[:id])
  end

  def update
    @nationality = Nationality.find(params[:id])
    if @nationality.update(nationality_params)
      flash[:notice] = "国籍を更新しました。"
      redirect_to admin_nationalities_path
    else
      render :edit
    end
  end

  def destroy
    @nationality = Nationality.find(params[:id])
    @nationality.destroy
    flash[:notice] = "国籍を削除しました。"
    redirect_to admin_nationalities_path
  end



  private

  def nationality_params
    params.require(:nationality).permit(:name)
  end


  def check_nationality_existence
    @nationality=Nationality.find_by(id: params[:id])
    unless @nationality
      redirect_to admin_nationalities_path
    end
  end

end

app/helpers/admin/nationalities_helper.rb
module Admin::NationalitiesHelper
end

app/views/admin/nationalities/edit.html.erb
<% if @nationality.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @nationality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class='container px-5 px-mt-5'>
  <div class="row p-1 mt-5">
    <h3>国名編集</h3>
  </div>
  <div class="row p-1 mt-5">
    <%= form_with(model: @nationality, url: admin_nationality_path(@nationality), method: :patch, class: 'form-group') do |f| %>
      <table cellpadding="10">
        <tr valign="top">
          <td>
            <%= f.label :name, "国名", class: 'form-label' %>
          </td>
          <td>
          </td>
          <td>
            <%= f.text_field :name, class: 'form-control', placeholder: '国名を入力してください' %>
          </td>
          <td>
            <%= f.submit "変更を保存する", class: 'btn btn-success' %>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/admin/nationalities/index.html.erb
<% if @nationality.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @nationality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>



<%= flash[:notice] %>
<div class='container px-5 px-mt-5'>
  <h4>国籍一覧・追加</h4>

  <div class="row ml-md-5">
    <b>国名</b>
  </div>
  <%= form_with(model: @nationality, url: admin_nationalities_path, class: 'form-group') do |f| %>
  <div class = "row ml-4">
  <div class="col-4">
    <div class="input-group mb-3">
      <%= f.text_field :name, class: 'form-control', placeholder: '国名' %>
    </div>
  </div>
  <div class="col-2">
    <div class="input-group-append">
       <%= f.submit "新規登録", class: 'btn btn-success' %>
    </div>
  </div>
  </div>
    <% end %>
</div>

<div class='container'>
  <div class="row  ml-5">
    <div class="col-md-8">
      <table class="table">
        <thead>
          <tr class="pl-5 table-warning">
            <th><b>国名</b></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @nationalities.each do |nationality| %>
            <tr>
              <td><%= link_to nationality.name, admin_nationality_path(nationality) %></td>
              <td><%= link_to '編集する', edit_admin_nationality_path(nationality), class: 'btn btn-success' %></td>
              <td><%= link_to '削除する', admin_nationality_path(nationality), data: {confirm: "削除しますか？"}, class: 'btn btn-danger', method: :delete %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="mx-auto"><%= paginate @nationalities %></div>
    </div>
  </div>
</div>

app/views/admin/nationalities/show.html.erb
<div class="container">
  <div class="row">
    <h1><strong><%= @nationality.name %>　一覧</strong></h1>
  </div>
  <div class="row">
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>User</th>
          <th>PLAYERS</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @nationality_post_players.each do |post_player| %>
        <tr>
          <td><%= link_to post_player.user.name, admin_user_path(post_player.user.id) %></td>
          <td><%= post_player.name %></td>
          <td><%= link_to "show", admin_post_player_path(post_player.id) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="mx-auto"><%= paginate @nationality_post_players %></div>
  </div>
</div>