config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }



  root to: 'public/homes#top'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :public do
    get 'homes/about'
    get "search" => "searches#search"

    resources :notifications, only: [:update]

    resources :nationalities, only: [:show]

    resources :post_players, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end


    get 'users/my_page' => 'users#my_page', as: :my_page
    get 'users/unsubscribe' =>'users#unsubscribe', as: :unsubscribe
    patch 'users/withdraw' =>'users#withdraw', as: :withdraw
    resources :users, only: [:index,:show,:edit,:update] do
      member do
        get :favorites
      end
      resource :relationship, only: [:create,:destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :cart_players,  only: [:index,:create,:update,:destroy] do
      collection do
        delete 'destroy_all'
      end
    end

  end



  namespace :admin do
    get '/' => 'homes#top'
    get "search" => "searches#search"

    resources :nationalities, only: [:show,:index,:edit,:create,:update,:destroy]

    resources :post_players, only: [:index,:show,:edit,:create,:update,:destroy] do
      resources :comments, only: [:destroy]
    end

    resources :users, only: [:index,:show,:edit,:update] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_players, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :cart_players#ベストイレブン機能
  has_many :notifications, dependent: :destroy # 通知機能追記

  has_many :relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :follower
  has_many :followers, through: :reverse_of_relationships, source: :follow

  validates :name, presence: true
  validates :email, presence: true


  def active_for_authentication?
    super && (is_active == true)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      user.name = "ゲスト"
    end
  end



  # フォローしたときの処理
  def follow(user_id)
    relationships.create(follower_id: user_id)
    #createの後に入れる引数はフォローされる人の引数を記述する。
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(follower_id: user_id).destroy
    #find_byの後に入れる引数はフォローされる人の引数を記述する。
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end



end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_user_existence, only: [:show, :edit, :update]

  def index
    @users=User.page(params[:page]).per(10)
  end

  def show
    @user=User.find(params[:id])
    @post_players=@user.post_players.page(params[:page]).per(10)
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "会員情報を更新しました。"
    else
      render :edit
    end
  end



private

  def user_params
    params.require(:user).permit(:name, :email, :is_active)
  end

  def check_user_existence
      @user=User.find_by(id: params[:id])
      unless @user
        redirect_to admin_users_path
      end
  end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_index.html.erb
<div class="row">
    <table class='table table-hover table-inverse'>
      <thead>
        <tr class="table-primary">
          <th>User</th>
          <th>Player Name</th>
          <th>Nationality</th>
          <th>Favorite</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <% post_players.each do |post_player| %>
          <tr>
            <td><%= link_to post_player.user.name, admin_user_path(post_player.user_id) %></td>
            <td><%= link_to post_player.name, admin_post_player_path(post_player.id) %></td>
            <td><%= post_player.nationality.name %></td>

            <!--<td id="favorite_btn_<%#= book.id %>"><%#= render 'favorites/favorite-btn', book: book %></td>-->
            <td>
              ♡<%= post_player.favorites.count %>
            </td>
            <td><%= link_to "Edit a player", edit_admin_post_player_path(post_player.id), class: "btn btn-success" %></td>
            <td><%= link_to "Delete", admin_post_player_path(post_player.id), class: "btn btn-danger", method: :delete, data: {confirm: "削除しますか？"} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="mx-auto"><%= paginate post_players %></div>

app/views/admin/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>



<div class="container">
    <div class="row">
      <%= form_with model: [:admin, @user], local: true , class: 'col-5 mx-auto my-5' do |f| %>
      <div class="row form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control user_name' %>
      </div>

      <div class="row form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.text_area :email, class: 'form-control user_email' %>
      </div>

      <div class="row form-group">
      <%= f.label :is_active, '会員ステータス' %>
        <div class="col-sm-9">
          <div class="custom-control custom-radio custom-control-inline">
          <%= f.radio_button :is_active, true, checked: @user.is_active == true, class: 'custom-control-input', id: 'status-active' %>
          <%= f.label :is_active, '有効', class: 'custom-control-label', for: 'status-active' %>
          </div>
          <div class="custom-control custom-radio custom-control-inline">
          <%= f.radio_button :is_active, false, checked: @user.is_active == false, class: 'custom-control-input', id: 'status-deleted' %>
          <%= f.label :is_active, '退会', class: 'custom-control-label', for: 'status-deleted' %>
          </div>
        </div>
      </div>

      <div class="row form-group">
        <%= f.submit "変更を保存", class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'layouts/search' %>
  </div>
  <div class="row">
    <div>
      <h1 class="my-3"><strong>Users</strong></h1>
    </div>
  </div>
  <div class="row">
    <table class='table table-hover table-inverse'>
      <thead>
        <tr class="table-primary">
          <th>User Name</th>
          <th>Post PLAYERS</th>
          <th>Follows</th>
          <th>Followers</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.name, admin_user_path(user.id) %></td>
            <td><%= link_to "#{user.post_players.count}", admin_user_path(user.id) %></td>
            <!--フォロー機能実装時に下記追加-->
            <td><%= link_to "#{user.followings.count}", admin_user_followings_path(user.id) %></td>
            <td><%= link_to "#{user.followers.count}", admin_user_followers_path(user.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="mx-auto"><%= paginate @users %></div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>


<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2 class="mt-3">Profile</h2>
      <table class='table'>
        <tr>
      	  <th>Name</th>
      	  <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>follow</th>
          <th><%= "#{@user.followings.count}" %></th>
          <!--管理者側にフォロー・フォロワー機能一覧は不要-->
        </tr>
        <tr>
          <th>follower</th>
          <th><%= "#{@user.followers.count}" %></th>
          <!--管理者側にフォロー・フォロワー機能一覧は不要-->
        </tr>
      </table>
      <div class="row">
          <%= link_to "Profile edit", edit_admin_user_path(@user.id), class: 'btn btn-success' %>
      </div>
    </div>
    <div class='col-md-8 offset-md-1'>
      <div class="row">
        <h2 class="mt-3">PLAYERS</h2>
      </div>
      <%= render 'admin/users/index',post_players: @post_players %>
        <!--共通テンプレート作成し、投稿者の投稿のみを一覧表示-->
    </div>
  </div>
</div>