config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }



  root to: 'public/homes#top'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :public do
    get 'homes/about'
    get "search" => "searches#search"

    resources :notifications, only: [:update]

    resources :nationalities, only: [:show]

    resources :post_players, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end


    get 'users/my_page' => 'users#my_page', as: :my_page
    get 'users/unsubscribe' =>'users#unsubscribe', as: :unsubscribe
    patch 'users/withdraw' =>'users#withdraw', as: :withdraw
    resources :users, only: [:index,:show,:edit,:update] do
      member do
        get :favorites
      end
      resource :relationship, only: [:create,:destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :cart_players,  only: [:index,:create,:update,:destroy] do
      collection do
        delete 'destroy_all'
      end
    end

  end



  namespace :admin do
    get '/' => 'homes#top'
    get "search" => "searches#search"

    resources :nationalities, only: [:show,:index,:edit,:create,:update,:destroy]

    resources :post_players, only: [:index,:show,:edit,:create,:update,:destroy] do
      resources :comments, only: [:destroy]
    end

    resources :users, only: [:index,:show,:edit,:update] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="container">
      <a class="navbar-brand" href="/"><span><i class="fa-regular fa-file"></i> PLAYERS FILE</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Post", new_public_post_player_path, class: "btn btn-primary" %>
          </li>
          <li>
            <%= link_to public_my_page_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> マイページ
            <%end %>
          </li>
          <li>
            <%=  link_to public_users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> ユーザー一覧
            <% end %>
          </li>
          <li>
            <%=  link_to public_post_players_path ,class: 'nav-link text-light' do %>
              <i class="fa-regular fa-file-lines"></i> 投稿一覧
            <% end %>
          </li>
          <li class="dropdown">
            <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa-regular fa-bell"></i>
              <span class="badge badge-danger"><%= current_user.notifications.where(read: false).count %></span>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <% if current_user.notifications.where(read: false).any? %>
                <small class="dropdown-item disabled">直近5件の未読の通知を表示しています</small>
                <% current_user.notifications.where(read: false).limit(5).order(created_at: :desc).each do |notification| %>
                  <%= link_to notification_message(notification), public_notification_path(notification), method: :patch, class: "dropdown-item" %>
                <% end %>
              <% else %>
                <span class="dropdown-item disabled">未読の通知はありません</span>
              <% end %>
            </div>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>

        <% elsif admin_signed_in? %>
            <li>
            <%=  link_to admin_users_path,class: 'nav-link text-light' do %>
              <i class="fa-solid fa-users"></i> 会員一覧
            <% end %>
            </li>
            <li>
            <%=  link_to admin_post_players_path,class: 'nav-link text-light' do %>
              <i class="fa-regular fa-file-lines"></i> 投稿一覧
            <% end %>
          　</li>
            <li>
            <%=  link_to admin_nationalities_path,class: 'nav-link text-light' do %>
              <i class="fa-regular fa-flag"></i> 国籍一覧
            <% end %>
            </li>
            <li>
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
            </li>

        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> ホーム
            <% end %>
          </li>
          <li>
            <%= link_to public_homes_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class= "container">
  <div class="row">
    <div class = "mx-auto">
      <% if admin_signed_in? %>
        <div class="search_form my-5">
        <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
          <%= f.text_field :word %>
          <%= f.select :range, options_for_select([['User'], ['PostPlayer'], ['Nationality']]) %>
          <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
          <%= f.submit "検索", class: "btn btn-primary" %>
        <% end %>
        </div>
      <% elsif user_signed_in? %>
        <div class="search_form my-5">
        <%= form_with url: public_search_path, local: true, method: :get do |f| %>
          <%= f.text_field :word %>
          <%= f.select :range, options_for_select([['User'], ['PostPlayer'], ['Nationality']]) %>
          <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
          <%= f.submit "検索", class: "btn btn-primary" %>
        <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayersFile</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/8ed54b1e33.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>